---

- name: Generate a random password
  set_fact:
    user_pass: "{{ pwd_alias }}"
  no_log: true

- name: Create non-root user group - "{{ group_name }}"
  ansible.builtin.group:
    name: "{{ group_name }}"
    system: false
    state: present
  register: group_status
  when: group_name is defined

- name: Set group_name to "{{ systemuser }}" if not defined
  set_fact:
    group_name: "{{ systemuser }}"
  when: group_name is not defined

- name: Create user "{{ systemuser }}"
  ansible.builtin.user:
    name: "{{ systemuser }}"
    comment: "{{ comments }}"
    append: false
    shell: /bin/bash
    password: "{{ user_pass | password_hash('sha512') }}"
    update_password: on_create
    group: "{{ group_name }}"
    state: present
  notify: Set password expiry
          Retrieve Password
  register: user_status
  become: true

- name: Ensure sudoers file is absent before creating a new one
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ systemuser }}"
    state: absent
  become: true

- name: Set up sudoers for "{{ systemuser }}"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ systemuser }}"
    line: "{{ systemuser }}   {{ sudoers }}"
    mode: "0440"
    create: true
    state: present
    validate: /usr/sbin/visudo -csf %s
  become: true
